-- LOTE 7: identificação e cadastro inteligente de clientes
-- Migração idempotente para tabela public.clientes + vínculo opcional com pedidos

BEGIN;

CREATE TABLE IF NOT EXISTS public.clientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  telefone text NOT NULL,
  telefone_normalizado text,
  email text,
  cep text,
  rua text,
  numero text,
  bairro text,
  cidade text,
  estado text,
  endereco text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.clientes
  ADD COLUMN IF NOT EXISTS telefone_normalizado text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS cep text,
  ADD COLUMN IF NOT EXISTS rua text,
  ADD COLUMN IF NOT EXISTS numero text,
  ADD COLUMN IF NOT EXISTS bairro text,
  ADD COLUMN IF NOT EXISTS cidade text,
  ADD COLUMN IF NOT EXISTS estado text,
  ADD COLUMN IF NOT EXISTS endereco text,
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

UPDATE public.clientes
SET telefone_normalizado = regexp_replace(coalesce(telefone, ''), '\\D', '', 'g')
WHERE coalesce(telefone_normalizado, '') = '';

CREATE INDEX IF NOT EXISTS idx_clientes_telefone ON public.clientes (telefone);
CREATE INDEX IF NOT EXISTS idx_clientes_telefone_normalizado ON public.clientes (telefone_normalizado);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'clientes_telefone_normalizado_unique'
      AND conrelid = 'public.clientes'::regclass
  ) THEN
    ALTER TABLE public.clientes
      ADD CONSTRAINT clientes_telefone_normalizado_unique UNIQUE (telefone_normalizado);
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_clientes_set_updated_at ON public.clientes;
CREATE TRIGGER trg_clientes_set_updated_at
BEFORE UPDATE ON public.clientes
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.pedidos
  ADD COLUMN IF NOT EXISTS cliente_id bigint;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'pedidos_cliente_id_fkey'
      AND conrelid = 'public.pedidos'::regclass
  ) THEN
    ALTER TABLE public.pedidos
      ADD CONSTRAINT pedidos_cliente_id_fkey
      FOREIGN KEY (cliente_id)
      REFERENCES public.clientes (id)
      ON DELETE SET NULL;
  END IF;
END $$;

COMMIT;
