-- Lote O.S. Fotos: tabela de metadados + bucket dedicado no Supabase Storage.

create table if not exists public.ordens_servico_fotos (
  id bigint generated by default as identity primary key,
  os_id bigint not null references public.ordens_servico(id) on delete cascade,
  storage_path text not null unique,
  ordem integer not null default 1,
  legenda text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_ordens_servico_fotos_os_id on public.ordens_servico_fotos(os_id);
create index if not exists idx_ordens_servico_fotos_os_id_ordem on public.ordens_servico_fotos(os_id, ordem);

grant select, insert, update, delete on public.ordens_servico_fotos to anon, authenticated;
grant usage, select on sequence public.ordens_servico_fotos_id_seq to anon, authenticated;

-- Bucket dedicado para fotos de Ordem de Serviço.
insert into storage.buckets (id, name, public)
values ('os-photos', 'os-photos', true)
on conflict (id) do nothing;

-- Políticas simples para CRUD via chave anon/authenticated (mesmo padrão operacional do painel).
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ordens_servico_fotos'
      and policyname = 'ordens_servico_fotos_select_all'
  ) then
    create policy ordens_servico_fotos_select_all
      on public.ordens_servico_fotos
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ordens_servico_fotos'
      and policyname = 'ordens_servico_fotos_insert_all'
  ) then
    create policy ordens_servico_fotos_insert_all
      on public.ordens_servico_fotos
      for insert
      to anon, authenticated
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ordens_servico_fotos'
      and policyname = 'ordens_servico_fotos_update_all'
  ) then
    create policy ordens_servico_fotos_update_all
      on public.ordens_servico_fotos
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ordens_servico_fotos'
      and policyname = 'ordens_servico_fotos_delete_all'
  ) then
    create policy ordens_servico_fotos_delete_all
      on public.ordens_servico_fotos
      for delete
      to anon, authenticated
      using (true);
  end if;
end $$;

alter table public.ordens_servico_fotos enable row level security;

-- Permissões de storage no bucket dedicado.
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'os_photos_storage_select'
  ) then
    create policy os_photos_storage_select
      on storage.objects
      for select
      to anon, authenticated
      using (bucket_id = 'os-photos');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'os_photos_storage_insert'
  ) then
    create policy os_photos_storage_insert
      on storage.objects
      for insert
      to anon, authenticated
      with check (bucket_id = 'os-photos');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'os_photos_storage_delete'
  ) then
    create policy os_photos_storage_delete
      on storage.objects
      for delete
      to anon, authenticated
      using (bucket_id = 'os-photos');
  end if;
end $$;
