-- Migration: cria tabela public.despesas (idempotente e segura)

BEGIN;

CREATE TABLE IF NOT EXISTS public.despesas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo text NOT NULL,
  valor numeric NOT NULL DEFAULT 0,
  descricao text,
  data timestamptz NOT NULL DEFAULT now(),
  pedido_id bigint NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS despesas_data_idx ON public.despesas (data);
CREATE INDEX IF NOT EXISTS despesas_pedido_id_idx ON public.despesas (pedido_id);

-- FK opcional/safe: adiciona apenas se pedidos(id) existir, com tipo compatível,
-- e a FK ainda não existir.
DO $$
DECLARE
  pedidos_id_type text;
BEGIN
  SELECT c.data_type
    INTO pedidos_id_type
  FROM information_schema.columns c
  WHERE c.table_schema = 'public'
    AND c.table_name = 'pedidos'
    AND c.column_name = 'id'
  LIMIT 1;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'pedidos'
      AND column_name = 'id'
  )
  AND pedidos_id_type = 'bigint'
  AND NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = 'public'
      AND t.relname = 'despesas'
      AND c.conname = 'despesas_pedido_id_fkey'
  ) THEN
    ALTER TABLE public.despesas
      ADD CONSTRAINT despesas_pedido_id_fkey
      FOREIGN KEY (pedido_id)
      REFERENCES public.pedidos(id)
      ON UPDATE CASCADE
      ON DELETE SET NULL;
  ELSIF pedidos_id_type IS NOT NULL AND pedidos_id_type <> 'bigint' THEN
    RAISE NOTICE 'FK despesas_pedido_id_fkey não criada: tipos incompatíveis (despesas.pedido_id=bigint, pedidos.id=%).', pedidos_id_type;
  END IF;
END $$;

COMMIT;

-- Verificação rápida
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name = 'despesas';
